# Generated by Django 3.0.8 on 2020-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poste', models.CharField(max_length=300)),
                ('Profil', models.CharField(max_length=300)),
                ('Compétences', models.CharField(max_length=1000)),
                ('Qualités', models.CharField(max_length=1000)),
                ('Contrat', models.CharField(max_length=300)),
                ('Lieu', models.CharField(max_length=300)),
                ('Durée', models.CharField(max_length=300)),
                ('Démarrage', models.CharField(max_length=300)),
                ('Expérience', models.CharField(max_length=300)),
            ],
        ),
    ]
