# Generated by Django 3.0.8 on 2020-07-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offres',
            old_name='Compétences',
            new_name='Competences',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Démarrage',
            new_name='Demarrage',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Durée',
            new_name='Duree',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Expérience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Qualités',
            new_name='Qualites',
        ),
    ]
