# Generated by Django 3.0.8 on 2020-07-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200725_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offres',
            old_name='Competences',
            new_name='Compétences',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Duree',
            new_name='Durée',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Demarrage',
            new_name='Démarrage',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Experience',
            new_name='Expérience',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='Qualites',
            new_name='Qualités',
        ),
    ]
